image: node:20.3.0

pipelines:
  default:
    - step:
        name: Install Dependencies
        caches:
          - node
        script:
          - cd backend
          - npm install
        services:
          - mongo
    - step:
        name: Build
        trigger: manual
        script:
          - cd backend
          - npm run build
    - step:
        name: Deploy
        trigger: manual
        script:
          - echo "Deploying application..."
definitions: 
  services: 
    mongo: 
      image: mongo
      environment:
        MONGO_INITDB_DATABASE: $MONGO_NAME
        MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
        MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
    # redis:
    #   image: redis
